config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  scope '/:locale' do
    resources :users do
      resources :wichlists
    end
    resources :sessions, only: %i[new create destroy]
    resources :password_resets
    resources :artists do
      resources :comments, only: %i[create destroy]
    end
    resources :songs
    resources :albums
    resources :agendas
    scope '/dashboards' do
      get 'admin/artists'
      get 'admin/sounds'
      get 'admin/albums'
      get 'admin/users'
      get 'admin/agendas'
      scope ':ie' do
        get 'admin/showartist'
        get 'admin/showsong'
        get 'admin/showalbum'
        get 'admin/showuser'
      end
    end
  end
end

app/models/agenda.rb
# frozen_string_literal: true

class Agenda < ApplicationRecord
  scope :most_recent, -> { order(date: :ASC) }
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  has_many :songs
  has_and_belongs_to_many :Users
  mount_uploader :photo_album, PhotoAlbumUploader
  paginates_per 18
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  has_and_belongs_to_many :songs
  has_many :comments
  mount_uploader :photo_artist, PhotoArtistUploader
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :artist
  belongs_to :user
  validates :body, length: { maximum: 200 }
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  has_and_belongs_to_many :artists
  belongs_to :album
  mount_uploader :photo_song, PhotoSongUploader
  mount_uploader :audio_url, AudioUrlUploader
  scope :most_recent, -> { order(created_at: :desc).limit(8) }
  paginates_per 9
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_validation :set_downcase_email
  after_initialize :default_role
  before_create { generate_token(:auth_token) }
  has_many :comments
  has_and_belongs_to_many :wichlists, class_name: 'Album'
  validates :role, inclusion: { in: %w[registered admin] }
  validates :mail, presence: true,
                   uniqueness: true
  has_secure_password
  def set_downcase_email
    self.mail = mail.downcase
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end
    while User.exists?(column => self[column])
  end
  end

  def default_role
    self.role ||= 'registered'
  end
  mount_uploader :profil_img, ProfilImgUploader
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[show edit update destroy]
  before_action :ensure_authenticated, only: %i[edit new create update destroy]
  before_action :ensure_admin?, only: %i[edit new create update destroy]

  def edit
    @songs = Song.all
    @artist_songs = @artist.songs.build
  end

  def new
    @artist = Artist.new
    @songs = Song.all
    @artist_songs = @artist.songs.build
   end

  def create
    @artist = Artist.new(artist_params)
    params[:song][:id].each do |sound|
      unless sound.empty?
        sound_trouve = Song.find(sound)
        @artist.songs << sound_trouve
      end
    end

    respond_to do |format|
      if @artist.save

        format.html { redirect_to admin_showartist_path(@artist), notice: 'Artist was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @artist.update(artist_params)
        @artist.songs.delete_all
        params[:song][:id].each do |sound|
          unless sound.empty?
            sound_trouve = Song.find(sound)
            @artist.songs << sound_trouve
          end
        end

        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @artist.destroy!
    respond_to do |format|
      format.js
    end
end

  def show
    @songs = @artist.songs
   end

  def index
    @artists = Artist.all
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :photo_artist, :bibliographie, :url_facebook, :mail)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/agendas_helper.rb
# frozen_string_literal: true

module AgendasHelper
end

app/helpers/albums_helper.rb
# frozen_string_literal: true

module AlbumsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/artist_helper.rb
# frozen_string_literal: true

module ArtistHelper
end

app/helpers/artists_helper.rb
# frozen_string_literal: true

module ArtistsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/role_helper.rb
# frozen_string_literal: true

module RoleHelper
  def onlyadmincanedit?
    if session[:user_id].present?
      current_user.role == 'admin'
    else
      false
   end
  end

  def can_edit?(user)
    case current_user.role
    when 'admin' then true
    when 'registered' then current_user == user
    else false

end
end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/songs_helper.rb
# frozen_string_literal: true

module SongsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/wichlists_helper.rb
# frozen_string_literal: true

module WichlistsHelper
end

app/views/artists/destroy.js.erb
Artist.RemoveArtist('<%= @artist.id %>')

app/views/artists/edit.html.erb
<body class="body_form">

  <!--
  ===================
  =========== bloc header document
  ===================
  -->
  <header>

    <!--
    ===================
    =========== navigation bar for telephone/tablet
    ===================
    -->
    <nav class="navebar-tel-tab" style="display:block;">
      <label class="label-chk" for="chk">&#9776;</label>
      <input type="checkbox" class="chk" name="chk" id="chk">
      <ul class="navebar-tel-tab--navigation">
        <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
        <li> <%= link_to('Dashbord',admin_sounds_path)  %> </li>

      </ul>
    </nav>
  </header>

  <main>
    <section class="cadre">

      <div class="text--center">
        <h1 class="gamma">Update Artist</h1>
      </div>
          <%=render(partial: "form_artist", locals: { artist: @artist,song: @songs,artist_songs: @artist_songs})  %>

    </section>
  </main>

  <div>
    <div class="progressBarControl__loadingControl" id="progressBarControl__loadingControl">
      <div class="progressBarControl__loading" id="progressBarControl__loading"> </div>
    </div>
    <div class="bloc_close_btn">
      <button class="btn" id="btn" type="button" name="button">CLOSE</button>
    </div>
  </div>



</body>

app/views/artists/index.html.erb
<!--
===================
=========== block block
===================
-->

<body>

  <!--
===================
=========== block header
===================
-->
  <header>

    <!--
  ===================
  =========== block navigation bar telephone/tablet
  ===================
  -->
    <nav class="navebar-tel-tab">
      <label class="label-chk" for="chk">&#9776;</label>
      <input type="checkbox" class="chk" name="chk" id="chk">
      <ul class="navebar-tel-tab--navigation">
        <li> <%= link_to translate("home"),root_path %></li>
        <li> <%= link_to(translate("latest"),songs_path) %> </li>
        <li> <%= link_to(translate("release"),albums_path) %> </li>
        <li> <%= link_to(translate("artist"),artists_path,class: "active") %></li>
        <li> <%= link_to(translate("event"),agendas_path) %> </li>
        <% if login?  %>
        <li> <%= link_to(translate("follower"), user_wichlists_path(current_user)) %> </li>
        <li> <%= link_to translate("profil"), edit_user_path(current_user) %> </li>
        <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
        <% end %>
        <% if onlyadmincanedit?  %>
        <li> <%= link_to("admin", admin_artists_path) %> </li>
        <% end %>
        <% I18n.available_locales.each do |locale| %>
        <li>  <%= link_to(locale,url_for(locale: locale),class:"nav-link") %> </li>
        <% end %>
      </ul>
    </nav>

    <!--
  ===================
  =========== block navigation bar laptop
  ===================
  -->
    <nav class="navebar_presentation">
      <div class="bloc_logo">
        <%= link_to(root_path) do %>
          <%= image_tag("logo.svg",class: "logo", alt: "logo nubian") %>
         <% end %>
      </div>
      <ul class="main-navigation">
        <li> <%= link_to(translate("latest"),songs_path) %> </li>
        <li> <%= link_to(translate("release"),albums_path) %> </li>
        <li> <%= link_to(translate("artist"),artists_path,class: "active") %></li>
        <li> <%= link_to(translate("event"),agendas_path) %> </li>
        <% if login?  %>
        <li> <%= link_to(translate("follower"), user_wichlists_path(current_user)) %> </li>
        <li> <%= link_to translate("profil"), edit_user_path(current_user) %> </li>
        <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
        <% end %>
        <% if onlyadmincanedit?  %>
        <li> <%= link_to("admin", admin_artists_path) %> </li>
        <% end %>
        <% I18n.available_locales.each do |locale| %>
        <li>  <%= link_to(locale,url_for(locale: locale),class:"nav-link") %> </li>
        <% end %>
      </ul>

    </nav>
  </header>

  <!--
===================
=========== list artistes
===================
-->
  <h1 class="number_artise"> <%= translate("nbrartiste") %> (<%= @artists.length %>)</h1>
  <div class="bloc_menu" id="bloc_menu">
    <ul class="menu_artiste">
      <% @artists.each  do |artist| %>
      <li class="bloc-photo_artiste"> <%= link_to(artist.name,artist_path(artist),class: "name_artiste",onmouseover: "affiche(this)",onmouseout: "cache(this)") %>
<%= image_tag artist.photo_artist,class: "photo_artiste cache" %>
      </li>
      <% end %>
    </ul>

  </div>


</body>

</html>

app/views/artists/new.html.erb
<body class="body_form">

  <!--
  ===================
  =========== bloc header document
  ===================
  -->
  <header>

    <!--
    ===================
    =========== navigation bar for telephone/tablet
    ===================
    -->
    <nav class="navebar-tel-tab" style="display:block;">
      <label class="label-chk" for="chk">&#9776;</label>
      <input type="checkbox" class="chk" name="chk" id="chk">
      <ul class="navebar-tel-tab--navigation">
        <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
        <li> <%= link_to('Dashbord',admin_sounds_path)  %> </li>

      </ul>
    </nav>
  </header>

  <main>
    <section class="cadre">

      <div class="text--center">
        <h1 class="gamma">New Artist</h1>
      </div>
        <%=render(partial: "form_artist", locals: { artist: @artist,song: @songs,artist_songs: @artist_songs})  %>

    </section>
  </main>

  <div>
    <div class="progressBarControl__loadingControl" id="progressBarControl__loadingControl">
      <div class="progressBarControl__loading" id="progressBarControl__loading"> </div>
    </div>
    <div class="bloc_close_btn">
      <button class="btn" id="btn" type="button" name="button">CLOSE</button>
    </div>
  </div>



</body>

app/views/artists/show.html.erb
<body onselectstart="return false" oncontextmenu="return false" ondragstart="return false" onMouseOver="window.status='..message perso .. '; return true;" >

  <!--
  ===================
  =========== svg icon
  ===================
  -->
  <svg style="display:none;">
    <defs>
      <symbol id="add_black">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="delete_black">
        <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
    </defs>
  </svg>
  <!--
  ===================
  =========== navigation bar for telephone/tablet
  ===================
  -->
  <nav class="navebar-tel-tab">
    <label class="label-chk" for="chk">&#9776;</label>
    <input type="checkbox" class="chk" name="chk" id="chk">
    <ul class="navebar-tel-tab--navigation">
      <li> <%= link_to translate("home"),root_path %></li>
      <li> <%= link_to(translate("latest"),songs_path) %> </li>
      <li> <%= link_to(translate("release"),albums_path) %> </li>
      <li> <%= link_to(translate("artist"),artists_path,class: "active") %></li>
      <li> <%= link_to(translate("event"),agendas_path) %> </li>
      <% if login?  %>
      <li> <%= link_to(translate("follower"), user_wichlists_path(current_user)) %> </li>
      <li> <%= link_to translate("profil"), edit_user_path(current_user) %> </li>
      <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
      <% end %>
      <% if onlyadmincanedit?  %>
      <li> <%= link_to("admin", admin_artists_path) %> </li>
      <% end %>
      <% I18n.available_locales.each do |locale| %>
      <li>  <%= link_to(locale,url_for(locale: locale),class:"nav-link") %> </li>
      <% end %>
    </ul>
  </nav>

  <!--
  ===================
  =========== bloc header document
  ===================
  -->
  <header style='background-image: url("<%=@artist.photo_artist %>");background-size:cover;background-attachment: fixed;' class="bloc_imagebackground">



    <!--
    ===================
    =========== bloc navigation bar for laptop
    ===================
    -->

    <nav class="navebar">

      <div class="navebar__absolute navebar_presentation navebar_presentation--artist ">
        <div class="bloc_logo">
          <%= link_to(root_path) do %>
            <%= image_tag("logo.svg",class: "logo", alt: "logo nubian") %>
           <% end %>
        </div>
        <ul class="main-navigation">
          <li> <%= link_to(translate("latest"),songs_path) %> </li>
          <li> <%= link_to(translate("release"),albums_path) %> </li>
          <li> <%= link_to(translate("artist"),artists_path,class: "active") %></li>
          <li> <%= link_to(translate("event"),agendas_path) %> </li>
          <% if login?  %>
          <li> <%= link_to(translate("follower"), user_wichlists_path(current_user)) %> </li>
          <li> <%= link_to translate("profil"), edit_user_path(current_user) %> </li>
          <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
          <% end %>
          <% if onlyadmincanedit?  %>
          <li> <%= link_to("admin", admin_artists_path) %> </li>
          <% end %>
          <% I18n.available_locales.each do |locale| %>
          <li>  <%= link_to(locale,url_for(locale: locale),class:"nav-link") %> </li>
          <% end %>
        </ul>
      </div>
    </nav>

  </header>

  <!--
  ===================
  =========== bloc content for to make border left and right
  ===================
  -->
  <div class="content content--artiste">

    <!--
    ===================
    =========== biographie artiste
    ===================
    -->
    <h1> Biography </h1>

    <div class="description__artiste">
      <div class="description__paragraphe">
        <p class="home__paragraphe "> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis
          nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
          dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
          cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <ul class="main-navigation">
          <%= link_to("facebook",@artist.url_facebook) %> </li>
         <%= link_to("instagramme",@artist.mail) %>
         </ul>
      </div>
    </div>

    <!--
      ===================
      ===========  Track
      ===================
      -->
    <h1 id="track"> Tracks </h1>
    <div class="track ">
      <div class="track-card">
        <div class="track-card--image">
          <%= image_tag(@artist.photo_artist, alt: "image goal" ) %>
        </div>

      </div>
      <div class="playlist">
        <table class="playlist__media">
          <tr>
            <th>#</th>
            <td class="playlist__piste">Play</td>
            <th>Track</th>
          </tr>
          <% i = 0 %>
          <% @songs.each do |song|  %>
          <tr class="playlist__media--line">
            <td class="playlist__piste"> piste<%=i %></td>
            <td class="playlist__piste"><button onclick="play('sound<%= i %>', this)">Play</button></td>
            <th class="playlist__name_music"><%= song.name  %></th>
          </tr>
          <% i= i + 1 %>
          <% end %>
        </table>
      </div>
    </div>

    <!--
      ===================
      ===========  video artiste
      ===================
      -->
    <h1> Video </h1>

    <div class="video-artite">
      <% @songs.each do |song|  %>
      <% if song.video_url.present? %>
      <%= song.video_url.html_safe  %>
      <% end %>
      <% end %>

    </div>

    <!--
      ===================
      ===========  ADD Comment
      ===================
      -->
      <h1> Comments </h1>
      <% if login? %>
      <div class="div_comments">

    <%= form_for([@artist, @artist.comments.build],html: {id: "form_comment",class: "add_comments"},remote: true) do |form| %>
      <%=image_tag(current_user.profil_img, class: "profil--img", alt: "image artiste" ) %>
        <%=form.text_area(:body, class: 'form-input',id: 'form-input',maxlength: 200) %>
      <%= form.submit  class: 'btn btn-primary' %>
  <% end %>
</div>
  <% end %>
    <!--
      ===================
      ===========  commentaires
      ===================
      -->
    <div class="comments" id="comments">

    <% @artist.comments.order(created_at: :asc).each do |comment| %>
    <div id=<%=comment.id %>>
      <%= image_tag(comment.user.profil_img, class: "profil--img", alt: "image artiste" ) %>
      <span class="auteur"> <%= comment.user.name %> </span>
      <span class="date"> <%= comment.created_at.strftime("%d %b %y at %I:%M") %></span>
      <p class="comments__paragraphe">
        <%= comment.body %>
      </p>
      <div class="card-button">
        <% if current_user == comment.user  %>
          <%= link_to 'Delete', artist_comment_path(current_user,comment.id), class: 'btn btn--wichlist dashbord_btn', role: 'button',method: :delete, remote: true %>
<% end %>
      </div>
        </div>
      <% end %>
    </div>




    <!-- ===================
            ===========  end content
            ===================
            -->
          </div>
          <div>
            <div class="progressBarControl__loadingControl" id="progressBarControl__loadingControl" onclick="clickProgress(window.currentPlay,this,event)">
              <span class="progressBarControl__loadingControl--artist"><%= @artist.name %> </span>
              <!--
                ===================
                ===========  sound audio
                ===================
                -->
                  <% i = 0 %>
                  <% @songs.each do |song|  %>
              <audio class="sound" id="sound<%= i %>" ontimeupdate="update(this)">
                <source src=<%= song.audio_url %>>

              </audio>
            <span class="progressBarControl__loadingControl--song" id="loadingControlsound<%= i %>" style="display:none"> <%= song.name %> </span>
          <% i= i + 1 %>
            <% end %>
              <div class="progressBarControl__loading" id="progressBarControl__loading"> </div>
            </div>
            <div class="bloc_close_btn" onclick= "closebar()">

            &times
            </div>
          </div>





</body>

</html>