config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  scope '/:locale' do
    resources :users do
      resources :wichlists
    end
    resources :sessions, only: %i[new create destroy]
    resources :password_resets
    resources :artists do
      resources :comments, only: %i[create destroy]
    end
    resources :songs
    resources :albums
    resources :agendas
    scope '/dashboards' do
      get 'admin/artists'
      get 'admin/sounds'
      get 'admin/albums'
      get 'admin/users'
      get 'admin/agendas'
      scope ':ie' do
        get 'admin/showartist'
        get 'admin/showsong'
        get 'admin/showalbum'
        get 'admin/showuser'
      end
    end
  end
end

app/models/agenda.rb
# frozen_string_literal: true

class Agenda < ApplicationRecord
  scope :most_recent, -> { order(date: :ASC) }
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  has_many :songs
  has_and_belongs_to_many :Users
  mount_uploader :photo_album, PhotoAlbumUploader
  paginates_per 18
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  has_and_belongs_to_many :songs
  has_many :comments
  mount_uploader :photo_artist, PhotoArtistUploader
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :artist
  belongs_to :user
  validates :body, length: { maximum: 200 }
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  has_and_belongs_to_many :artists
  belongs_to :album
  mount_uploader :photo_song, PhotoSongUploader
  mount_uploader :audio_url, AudioUrlUploader
  scope :most_recent, -> { order(created_at: :desc).limit(8) }
  paginates_per 9
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_validation :set_downcase_email
  after_initialize :default_role
  before_create { generate_token(:auth_token) }
  has_many :comments
  has_and_belongs_to_many :wichlists, class_name: 'Album'
  validates :role, inclusion: { in: %w[registered admin] }
  validates :mail, presence: true,
                   uniqueness: true
  has_secure_password
  def set_downcase_email
    self.mail = mail.downcase
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end
    while User.exists?(column => self[column])
  end
  end

  def default_role
    self.role ||= 'registered'
  end
  mount_uploader :profil_img, ProfilImgUploader
end

app/controllers/wichlists_controller.rb
# frozen_string_literal: true

class WichlistsController < ApplicationController
  before_action :ensure_authenticated
  def create
    @album = Album.find(params[:album_id])
    current_user.wichlists << @album
    respond_to do |format|
      format.html { redirect_to album_path(@album) }
      format.js
    end
  end

  def destroy
    @wichlist = current_user.wichlists.find(params[:id])
    current_user.wichlists.destroy params[:id]
    respond_to do |format|
      # In this format call, the flash message is being passed directly to
      # redirect_to().  It's a caonvenient way of setting a flash notice or
      # alert without referencing the flash Hash explicitly.
      format.html { redirect_to user_wichlists_path(current_user) }
      format.js
    end
  end

  def index
    @wichlists = current_user.wichlists
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/agendas_helper.rb
# frozen_string_literal: true

module AgendasHelper
end

app/helpers/albums_helper.rb
# frozen_string_literal: true

module AlbumsHelper
end

app/helpers/artist_helper.rb
# frozen_string_literal: true

module ArtistHelper
end

app/helpers/artists_helper.rb
# frozen_string_literal: true

module ArtistsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/role_helper.rb
# frozen_string_literal: true

module RoleHelper
  def onlyadmincanedit?
    if session[:user_id].present?
      current_user.role == 'admin'
    else
      false
   end
  end

  def can_edit?(user)
    case current_user.role
    when 'admin' then true
    when 'registered' then current_user == user
    else false

end
end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/songs_helper.rb
# frozen_string_literal: true

module SongsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/wichlists_helper.rb
# frozen_string_literal: true

module WichlistsHelper
end

app/views/wichlists/destroy.js.erb
Wichlist.Removealbum('<%= @wichlist.id %>')

app/views/wichlists/index.html.erb
  <body class="follower" onselectstart="return false" oncontextmenu="return false" ondragstart="return false" onMouseOver="window.status='..message perso .. '; return true;" >

  <!--
  ===================
  =========== svg icon
  ===================
  -->
  <svg style="display:none;">
    <defs>
      <symbol id="add_black">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="delete_black">
        <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
    </defs>
  </svg>

  <!--
  ===================
  =========== bloc header document
  ===================
  -->
  <header>

    <!--
    ===================
    =========== navigation bar for telephone/tablet
    ===================
    -->
    <nav class="navebar-tel-tab" style="display: block">
      <label class="label-chk" for="chk">&#9776;</label>
      <input type="checkbox" class="chk" name="chk" id="chk">
      <ul class="navebar-tel-tab--navigation">
        <li> <%= link_to translate("home"),root_path %></li>
        <li> <%= link_to(translate("latest"),songs_path) %> </li>
        <li> <%= link_to(translate("release"),albums_path,class: "active") %> </li>
        <li> <%= link_to(translate("artist"),artists_path) %></li>
        <li> <%= link_to(translate("event"),agendas_path) %> </li>
        <% if onlyadmincanedit?  %>
        <li> <%= link_to("admin", admin_artists_path) %> </li>
        <% end %>
        <% I18n.available_locales.each do |locale| %>
        <li>  <%= link_to(locale,url_for(locale: locale),class:"nav-link") %> </li>
        <% end %>
      </ul>
    </nav>


  </header>

  <!--
  ===================
  =========== bloc content for to make border left and right
  ===================
  -->
  <div class="content">
    <!--
      ===================
      ===========  Track
      ===================
      -->
    <h1 id="track"> <%= translate("followeralbum") %></h1>
    <% @wichlists.each do |wichlist| %>
    <div>
    <div class="track " id="track<%= wichlist.id %>">
      <div class="track-card">
        <p>  <%= wichlist.name %>  </p>
        <div class="track-card--image">
          <%= image_tag(wichlist.photo_album, alt: "image goal" ) %>
        </div>
        <div class="card-button">

            <%= link_to 'Delete', user_wichlist_path(current_user,wichlist.id), class: 'btn btn--wichlist', role: 'button',method: :delete, remote: true %>

        </div>
      </div>
      <div class="playlist">
        <table class="playlist__media">
          <tr>
            <th>#</th>
            <td class="playlist__piste">Play</td>
            <th>Track</th>
          </tr>
          <% i = 0 %>
          <% wichlist.songs.each do |song|  %>
          <tr class="playlist__media--line">
            <td class="playlist__piste"> piste<%=i %></td>
            <td class="playlist__piste"><button onclick="play('sound<%= i %>', this)">Play</button></td>
            <th class="playlist__name_music"><%= song.name  %></th>
          </tr>
          <% i= i + 1 %>
          <% end %>
        </table>
      </div>
    </div>


<!-- ===================
      ===========  end content
      ===================
      -->
    </div>
      </div>
    <div>
      <div  id="progressBarControl__loadingControl" onclick="clickProgress(window.currentPlay,this,event)">
        <% i = 0 %>
        <% wichlist.songs.each do |song|  %>
    <audio class="sound" id="sound<%= i %>" ontimeupdate="update(this)">
      <source src=<%= song.audio_url %>>
    </audio>

    <% i= i + 1 %>
    <% end %>


      </div>

    </div>
    <% end %>



    <!-- ===================
            ===========  end content
            ===================
            -->




</body>

</html>