config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  scope '/:locale' do
    resources :users do
      resources :wichlists
    end
    resources :sessions, only: %i[new create destroy]
    resources :password_resets
    resources :artists do
      resources :comments, only: %i[create destroy]
    end
    resources :songs
    resources :albums
    resources :agendas
    scope '/dashboards' do
      get 'admin/artists'
      get 'admin/sounds'
      get 'admin/albums'
      get 'admin/users'
      get 'admin/agendas'
      scope ':ie' do
        get 'admin/showartist'
        get 'admin/showsong'
        get 'admin/showalbum'
        get 'admin/showuser'
      end
    end
  end
end

app/models/agenda.rb
# frozen_string_literal: true

class Agenda < ApplicationRecord
  scope :most_recent, -> { order(date: :ASC) }
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  has_many :songs
  has_and_belongs_to_many :Users
  mount_uploader :photo_album, PhotoAlbumUploader
  paginates_per 18
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  has_and_belongs_to_many :songs
  has_many :comments
  mount_uploader :photo_artist, PhotoArtistUploader
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :artist
  belongs_to :user
  validates :body, length: { maximum: 200 }
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  has_and_belongs_to_many :artists
  belongs_to :album
  mount_uploader :photo_song, PhotoSongUploader
  mount_uploader :audio_url, AudioUrlUploader
  scope :most_recent, -> { order(created_at: :desc).limit(8) }
  paginates_per 9
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_validation :set_downcase_email
  after_initialize :default_role
  before_create { generate_token(:auth_token) }
  has_many :comments
  has_and_belongs_to_many :wichlists, class_name: 'Album'
  validates :role, inclusion: { in: %w[registered admin] }
  validates :mail, presence: true,
                   uniqueness: true
  has_secure_password
  def set_downcase_email
    self.mail = mail.downcase
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end
    while User.exists?(column => self[column])
  end
  end

  def default_role
    self.role ||= 'registered'
  end
  mount_uploader :profil_img, ProfilImgUploader
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/agendas_helper.rb
# frozen_string_literal: true

module AgendasHelper
end

app/helpers/albums_helper.rb
# frozen_string_literal: true

module AlbumsHelper
end

app/helpers/artist_helper.rb
# frozen_string_literal: true

module ArtistHelper
end

app/helpers/artists_helper.rb
# frozen_string_literal: true

module ArtistsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/role_helper.rb
# frozen_string_literal: true

module RoleHelper
  def onlyadmincanedit?
    if session[:user_id].present?
      current_user.role == 'admin'
    else
      false
   end
  end

  def can_edit?(user)
    case current_user.role
    when 'admin' then true
    when 'registered' then current_user == user
    else false

end
end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/songs_helper.rb
# frozen_string_literal: true

module SongsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/wichlists_helper.rb
# frozen_string_literal: true

module WichlistsHelper
end

app/views/admin/_navadmin.html.erb
<header>
  <nav>
    <ul class="main__admin">
      <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
      <li> <%= link_to(translate("viewmodification"),artists_path) %> </li>
    </ul>
  </nav>
</header>

app/views/admin/agendas.html.erb
<!--
===================
=========== block body document
===================
-->

<body class="admin">

  <!--
  ===================
  =========== svg icon
  ===================
  -->
  <svg style="display:none;">
    <defs>
      <symbol id="add_black">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="delete_black">
        <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="edit-svg">
        <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
    </defs>
  </svg>

  <!--
===================
=========== block header
===================
-->
  <%= render(partial: "navadmin")  %>

  <!--
  ===================
  =========== dashbord
  ===================
  -->

  <div class="content">
    <h2 id="dashbord">04. Dashbord </h2>
    <div class="block-dashbord">
      <div class="dashbord">
        <%= link_to admin_artists_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Artiste
        </button>
        <% end %>

        <%= link_to admin_users_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Users
        </button>
        <% end %>

        <%= link_to admin_sounds_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Sound
        </button>
        <% end %>

      <%= link_to admin_albums_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Album
        </button>
          <% end %>

          <%= link_to admin_agendas_path do %>
            <button class="btn btn--svg dashbord_btn">
              <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                <use xlink:href="#edit-svg"></use>
              </svg>Agenda
            </button>
              <% end %>
      </div>
      <div class="bloc-panels-dashbord">
        <%= link_to(new_agenda_path) do %>
        <div class="panels-dashbord">
          <h2 id="titre-dashbord"> Agenda
            <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
              <use xlink:href="#add_black"></use>
            </svg>
          </h2>
<% end %>

        </div>
        <div class="playlist">
          <table class="playlist__media">
            <tr>
              <th>Name</th>
              <th>Edit</th>
              <th>Delete</th>
            </tr>
              <% @agendas.each do |agenda| %>
            <tr>
              <td>  <%=agenda.name %>  </td>
              <td>
                <%= link_to(edit_agenda_path(agenda.id))  do%>
                <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#edit-svg"></use>
                </svg>
              </td>
                <% end %>
              <td id="agenda-<%= agenda.id %>">
                <%= link_to(agenda_path(agenda.id),method: :delete, remote: true) do %>
                <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#delete_black"></use>
                </svg>
                <% end %>
              </td>
            </tr>
              <% end %>
          </table>
        </div>
      </div>
    </div>



</body>

</html>

app/views/admin/albums.html.erb
<!--
===================
=========== block body document
===================
-->

<body class="admin">

  <!--
  ===================
  =========== svg icon
  ===================
  -->
  <svg style="display:none;">
    <defs>
      <symbol id="add_black">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="delete_black">
        <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="edit-svg">
        <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
    </defs>
  </svg>

  <!--
===================
=========== block header
===================
-->
  <%= render(partial: "navadmin")  %>

  <!--
  ===================
  =========== dashbord
  ===================
  -->

  <div class="content">
    <h2 id="dashbord">04. Dashbord </h2>
    <div class="block-dashbord">
      <div class="dashbord">
        <%= link_to admin_artists_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Artiste
        </button>
        <% end %>

        <%= link_to admin_users_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Users
        </button>
        <% end %>

        <%= link_to admin_sounds_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Sound
        </button>
        <% end %>

      <%= link_to admin_albums_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Album
        </button>
          <% end %>

          <%= link_to admin_agendas_path do %>
            <button class="btn btn--svg dashbord_btn">
              <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                <use xlink:href="#edit-svg"></use>
              </svg>Agenda
            </button>
              <% end %>
      </div>
      <div class="bloc-panels-dashbord">
        <%= link_to(new_album_path) do %>
        <div class="panels-dashbord">
          <h2 id="titre-dashbord"> Album
            <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
              <use xlink:href="#add_black"></use>
            </svg>
          </h2>
<% end %>
        </div>
        <div class="playlist">
          <table class="playlist__media">
            <tr>
              <th>Name</th>
              <th>Edit</th>
              <th>Delete</th>
            </tr>
              <% @albums.each do |album| %>
            <tr>
              <td>  <%=album.name %>  </td>
              <td>
                <%= link_to(edit_album_path(album.id))  do%>
                <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#edit-svg"></use>
                </svg>
              </td>
                <% end %>
              <td id="album-<%= album.id %>">
                <%= link_to(album_path(album.id),method: :delete, remote: true) do %>
                <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#delete_black"></use>
                </svg>
                <% end %>
              </td>
            </tr>
              <% end %>
          </table>
        </div>
      </div>
    </div>



</body>

</html>

app/views/admin/artists.html.erb
<!--
===================
=========== block body document
===================
-->

<body class="admin">

  <!--
  ===================
  =========== svg icon
  ===================
  -->
  <svg style="display:none;">
    <defs>
      <symbol id="add_black">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="delete_black">
        <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="edit-svg">
        <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
    </defs>
  </svg>

  <!--
===================
=========== block header
===================
-->
  <%= render(partial: "navadmin")  %>

  <!--
  ===================
  =========== dashbord
  ===================
  -->

  <div class="content">
    <h2 id="dashbord">04. Dashbord </h2>
    <div class="block-dashbord">
      <div class="dashbord">
        <%= link_to admin_artists_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Artiste
        </button>
        <% end %>

        <%= link_to admin_users_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Users
        </button>
        <% end %>

        <%= link_to admin_sounds_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Sound
        </button>
        <% end %>

      <%= link_to admin_albums_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Album
        </button>
          <% end %>

          <%= link_to admin_agendas_path do %>
            <button class="btn btn--svg dashbord_btn">
              <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                <use xlink:href="#edit-svg"></use>
              </svg>Agenda
            </button>
              <% end %>
      </div>
      <div class="bloc-panels-dashbord">
        <%= link_to(new_artist_path) do %>
        <div class="panels-dashbord">
          <h2 id="titre-dashbord"> Artiste
            <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
              <use xlink:href="#add_black"></use>
            </svg>
          </h2>
<% end %>
        </div>
        <div class="playlist">
          <table class="playlist__media">
            <tr>
              <th>Name</th>
              <th>Edit</th>
              <th>Delete</th>
            </tr>
            <% @artists.each do |artist| %>
            <tr>
              <td> <%=artist.name %>    </td>

              <td>
                <%= link_to(edit_artist_path(artist.id))  do%>
                 <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#edit-svg"></use>
                </svg>
                <% end %>
              </td>

              <td id="artist-<%= artist.id %>">
                <%= link_to(artist_path(artist.id),method: :delete, remote: true) do %>
                <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#delete_black"></use>
                </svg>
                <% end %>
              </td>

            </tr>
          <% end %>
          </table>
        </div>
      </div>
    </div>



</body>

</html>

app/views/admin/showalbum.html.erb
<body class="show">
<header>
  <nav>
    <ul class="main__admin">
      <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
      <li> <%= link_to('Dashbord',admin_sounds_path)  %> </li>
    </ul>
  </nav>
</header>

<%= render partial: 'card_create_album', locals: { album: @album } %>
</body>

app/views/admin/showartist.html.erb
<body class="show">
<header>
  <nav>
    <ul class="main__admin">
      <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
      <li> <%= link_to('Dashbord',admin_sounds_path)  %> </li>
    </ul>
  </nav>
</header>

<%= render partial: 'card_create_artist', locals: { artist: @artist } %>
</body>

app/views/admin/sounds.html.erb
<!--
===================
=========== block body document
===================
-->

<body class="admin">

  <!--
  ===================
  =========== svg icon
  ===================
  -->
  <svg style="display:none;">
    <defs>
      <symbol id="add_black">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="delete_black">
        <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="edit-svg">
        <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
    </defs>
  </svg>

  <!--
===================
=========== block header
===================
-->
  <%= render(partial: "navadmin")  %>

  <!--
  ===================
  =========== dashbord
  ===================
  -->

  <div class="content">
    <h2 id="dashbord">04. Dashbord </h2>
    <div class="block-dashbord">
      <div class="dashbord">
        <%= link_to admin_artists_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Artiste
        </button>
        <% end %>

        <%= link_to admin_users_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Users
        </button>
        <% end %>

        <%= link_to admin_sounds_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Sound
        </button>
        <% end %>

      <%= link_to admin_albums_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Album
        </button>
          <% end %>

          <%= link_to admin_agendas_path do %>
            <button class="btn btn--svg dashbord_btn">
              <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                <use xlink:href="#edit-svg"></use>
              </svg>Agenda
            </button>
              <% end %>
      </div>
      <div class="bloc-panels-dashbord">
        <%= link_to(new_song_path) do %>
        <div class="panels-dashbord">
          <h2 id="titre-dashbord">Sound
            <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
              <use xlink:href="#add_black"></use>
            </svg>
          </h2>
<% end %>
        </div>
        <div class="playlist">
          <table class="playlist__media">
            <tr>
              <th>Name</th>
              <th>Edit</th>
              <th>Delete</th>
            </tr>
            <% @songs.each do |song| %>
            <tr>
              <td>  <%=song.name %>    </td>
              <td>
                <%= link_to(edit_song_path(song.id))  do%>
                <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#edit-svg"></use>
                </svg>
              </td>
              <% end %>
              <td id="song-<%= song.id %>">

<%= link_to(song_path(song.id),method: :delete, remote: true) do %>
                <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#delete_black"></use>
                </svg>
                  <% end %>
              </td>
            </tr>
          <% end %>
          </table>
        </div>
      </div>



</body>

</html>

app/views/admin/users.html.erb
<!--
===================
=========== block body document
===================
-->

<body class="admin">

  <!--
  ===================
  =========== svg icon
  ===================
  -->
  <svg style="display:none;">
    <defs>
      <symbol id="add_black">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="delete_black">
        <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
      <symbol id="edit-svg">
        <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z" />
        <path d="M0 0h24v24H0z" fill="none" />
      </symbol>
    </defs>
  </svg>

  <!--
===================
=========== block header
===================
-->
  <%= render(partial: "navadmin")  %>

  <!--
  ===================
  =========== dashbord
  ===================
  -->

  <div class="content">
    <h2 id="dashbord">04. Dashbord </h2>
    <div class="block-dashbord">
      <div class="dashbord">
        <%= link_to admin_artists_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Artiste
        </button>
        <% end %>

        <%= link_to admin_users_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Users
        </button>
        <% end %>

        <%= link_to admin_sounds_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Sound
        </button>
        <% end %>

      <%= link_to admin_albums_path do %>
        <button class="btn btn--svg dashbord_btn">
          <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
            <use xlink:href="#edit-svg"></use>
          </svg>Album
        </button>
          <% end %>
          <%= link_to admin_agendas_path do %>
            <button class="btn btn--svg dashbord_btn">
              <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                <use xlink:href="#edit-svg"></use>
              </svg>Agenda
            </button>
              <% end %>
      </div>
      <div class="bloc-panels-dashbord">
        <%= link_to(new_user_path) do %>
        <div class="panels-dashbord">
          <h2 id="titre-dashbord"> User
            <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
              <use xlink:href="#add_black"></use>
            </svg>
          </h2>
<% end %>
        </div>
        <div class="playlist">
          <table class="playlist__media">
            <tr>
              <th>Name</th>
              <th>Edit</th>
              <th>Delete</th>
            </tr>

            <% @users.each do |user| %>
            <tr>
              <td> <%=user.name %>     </td>

              <td>
<%= link_to(edit_user_path(user.id))  do%>
                <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#edit-svg"></use>
                </svg>
              </td>
              <% end %>
              <td id="user-<%= user.id %>">
                <%= link_to(user_path(user.id),method: :delete, remote: true) do %>
                <svg fill="#bbc1c6" height="18" viewBox="0 0 24 24" width="18" xmlns="http://www.w3.org/2000/svg">
                  <use xlink:href="#delete_black"></use>
                </svg>
                  <% end %>
              </td>
            </tr>
          <% end %>
          </table>
        </div>
      </div>
    </div>



</body>

</html>