config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  scope '/:locale' do
    resources :users do
      resources :wichlists
    end
    resources :sessions, only: %i[new create destroy]
    resources :password_resets
    resources :artists do
      resources :comments, only: %i[create destroy]
    end
    resources :songs
    resources :albums
    resources :agendas
    scope '/dashboards' do
      get 'admin/artists'
      get 'admin/sounds'
      get 'admin/albums'
      get 'admin/users'
      get 'admin/agendas'
      scope ':ie' do
        get 'admin/showartist'
        get 'admin/showsong'
        get 'admin/showalbum'
        get 'admin/showuser'
      end
    end
  end
end

app/models/agenda.rb
# frozen_string_literal: true

class Agenda < ApplicationRecord
  scope :most_recent, -> { order(date: :ASC) }
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  has_many :songs
  has_and_belongs_to_many :Users
  mount_uploader :photo_album, PhotoAlbumUploader
  paginates_per 18
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  has_and_belongs_to_many :songs
  has_many :comments
  mount_uploader :photo_artist, PhotoArtistUploader
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :artist
  belongs_to :user
  validates :body, length: { maximum: 200 }
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  has_and_belongs_to_many :artists
  belongs_to :album
  mount_uploader :photo_song, PhotoSongUploader
  mount_uploader :audio_url, AudioUrlUploader
  scope :most_recent, -> { order(created_at: :desc).limit(8) }
  paginates_per 9
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_validation :set_downcase_email
  after_initialize :default_role
  before_create { generate_token(:auth_token) }
  has_many :comments
  has_and_belongs_to_many :wichlists, class_name: 'Album'
  validates :role, inclusion: { in: %w[registered admin] }
  validates :mail, presence: true,
                   uniqueness: true
  has_secure_password
  def set_downcase_email
    self.mail = mail.downcase
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end
    while User.exists?(column => self[column])
  end
  end

  def default_role
    self.role ||= 'registered'
  end
  mount_uploader :profil_img, ProfilImgUploader
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :ensure_authenticated, only: %i[edit update destroy]
  before_action :authorize_to_edit_user, only: %i[edit update destroy]
  def edit
    @user = User.find(params[:id])
   end

  def new
    @user = User.new
   end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      redirect_to admin_showuser_path(@user), notice: 'User was successfully created.'
    else
      render :new

  end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        # In this format call, the flash message is being passed directly to
        # redirect_to().  It's a caonvenient way of setting a flash notice or
        # alert without referencing the flash Hash explicitly.
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy!
    respond_to do |format|
      format.js
    end
end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :mail, :profil_img, :password)
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/agendas_helper.rb
# frozen_string_literal: true

module AgendasHelper
end

app/helpers/albums_helper.rb
# frozen_string_literal: true

module AlbumsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/artist_helper.rb
# frozen_string_literal: true

module ArtistHelper
end

app/helpers/artists_helper.rb
# frozen_string_literal: true

module ArtistsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/role_helper.rb
# frozen_string_literal: true

module RoleHelper
  def onlyadmincanedit?
    if session[:user_id].present?
      current_user.role == 'admin'
    else
      false
   end
  end

  def can_edit?(user)
    case current_user.role
    when 'admin' then true
    when 'registered' then current_user == user
    else false

end
end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/songs_helper.rb
# frozen_string_literal: true

module SongsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/wichlists_helper.rb
# frozen_string_literal: true

module WichlistsHelper
end

app/views/users/destroy.html.erb
User.RemoveUser('<%= @user.id %>')

app/views/users/edit.html.erb
<body class="body_form">

  <!--
  ===================
  =========== bloc header document
  ===================
  -->
  <header>

    <!--
    ===================
    =========== navigation bar for telephone/tablet
    ===================
    -->
    <nav class="navebar-tel-tab" style="display:block;">
      <label class="label-chk" for="chk">&#9776;</label>
      <input type="checkbox" class="chk" name="chk" id="chk">
      <ul class="navebar-tel-tab--navigation">
      <li>  <%= link_to("LOG IN",new_session_path)  %> </li>
        <li> <%= link_to("LATEST",songs_path) %> </li>

      </ul>
    </nav>
  </header>

  <main>
    <section class="cadre">

      <div class="text--center">
        <h1 class="gamma">Update User</h1>
      </div>
        <%=render(partial: "form_usr", locals: { user: @user})  %>

    </section>
  </main>

  



</body>

app/views/users/index.html.erb
<body class="body_form">

  <!--
  ===================
  =========== bloc header document
  ===================
  -->
  <header>

    <!--
    ===================
    =========== navigation bar for telephone/tablet
    ===================
    -->
    <nav class="navebar-tel-tab" style="display:block;">
      <label class="label-chk" for="chk">&#9776;</label>
      <input type="checkbox" class="chk" name="chk" id="chk">
      <ul class="navebar-tel-tab--navigation">
        <li> <a href="log_in.html">Log In </a></li>
        <li> <a href="album.html"> Visite </a></li>

      </ul>
    </nav>
  </header>

  <main>
    <section class="cadre">
      <div class="text--center">
        <h1 class="gamma">Sign up</h1>
      </div>
      <form action="#no-action" method="post" enctype="multipart/form-data">
        <div class="input-group" id="bloc-name">
          <label class="input-group__label" for="name">Name</label>
          <input type="text" class="input-group__field" id="name" name="name" placeholder="Kandji">
        </div>
        <div class="input-group" id="bloc-email">
          <label class="input-group__label" for="email">Email address</label>
          <input type="email" class="input-group__field" id="email" name="email" placeholder="kandji.k66@gmail.com">
        </div>
        <div class="input-group" id="bloc-password">
          <label class="input-group__label" for="password">Passeword</label>
          <input type="password" class="input-group__field" id="password" name="password" placeholder="********">
        </div>
        <div class="input-group">
          <label class="input-group__label" for="password2">Verification Password</label>
          <input type="password" class="input-group__field" id="password2" name="password2" placeholder="********">
        </div>
        <div class="input-group" id="bloc-file">
          <label class="input-group__label" for="img_profil"> Choice a profil picture </label>
          <input type="file" class="input-group__field" id="img_profil" name="img_profil">
        </div>
        <div class="prompt">
          <button type="button" class="btn btn--primary prompt__confirm">Sign up</button>
        </div>
      </form>
    </section>
  </main>

  <div>
    <div class="progressBarControl__loadingControl" id="progressBarControl__loadingControl">
      <div class="progressBarControl__loading" id="progressBarControl__loading"> </div>
    </div>
    <div class="bloc_close_btn">
      <button class="btn" id="btn" type="button" name="button">CLOSE</button>
    </div>
  </div>


  <!--
  ===================
  ===========
script js
  ===================
  -->

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script src="js/style.js"> </script>
</body>

app/views/users/new.html.erb
<body class="body_form">

  <!--
  ===================
  =========== bloc header document
  ===================
  -->
  <header>

    <!--
    ===================
    =========== navigation bar for telephone/tablet
    ===================
    -->
    <nav class="navebar-tel-tab" style="display:block;">
      <label class="label-chk" for="chk">&#9776;</label>
      <input type="checkbox" class="chk" name="chk" id="chk">
      <ul class="navebar-tel-tab--navigation">
        <li> <%= link_to translate("home"),root_path %></li>
        <li> <%= link_to translate("signup"),new_user_path %></li>


      </ul>
    </nav>
  </header>

  <main>
    <section class="cadre">

      <div class="text--center">
        <h1 class="gamma">Sign up</h1>
      </div>
        <%=render(partial: "form_usr", locals: { user: @user})  %>
    </section>
  </main>





</body>

app/views/users/show.html.erb
<body class="show">
<header>
  <nav>
    <ul class="main__admin">
      <li> <%= link_to translate("logout"), session_path(current_user),method: :delete %> </li>
      <li> <%= link_to translate("home"),root_path %></li>
    </ul>
  </nav>
</header>

<%= render partial: 'card_create_user', locals: { user: @user } %>
</body>